include:
  - project: 'acc-co/devops/python/acc-py-devtools'
    file: 'acc_py_devtools/templates/gitlab-ci/python.yml'


stages:
  - Code Quality
  - Unit Tests
  - Build Wheel
  - Documentation
  - Upload Release

variables:
  ACCPY_IMAGE_CC7_2020_11: registry.cern.ch/acc/acc-py_cc7_openjdk11_gui_ci:2020.11
  ACCPY_IMAGE_CC7_2021_12: registry.cern.ch/acc/acc-py_cc7_openjdk11_gui_ci:2021.12
  ACCPY_IMAGE_CS8_2020_11: registry.cern.ch/acc/acc-py_cs8_openjdk11_gui_ci:2020.11
  ACCPY_IMAGE_CS8_2021_12: registry.cern.ch/acc/acc-py_cs8_openjdk11_gui_ci:2021.12
  ACCPY_IMAGE_INFRASTRUCTURE: registry.cern.ch/acc/acc-py_cc7_openjdk11_gui_ci:pro
  project_name: comrad  # Required by acc-py templates

.init_sequence: &init_sequence
- git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch".insteadOf ssh://git@gitlab.cern.ch:7999
- pip install -U pip

before_script:
  - *init_sequence

.matrix_job:
  image: $CURRENT_BASE_IMAGE
  parallel:
    matrix:
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CC7_2020_11
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CC7_2021_12
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CS8_2020_11
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CS8_2021_12

flake8:
  extends: .matrix_job
  stage: Code Quality
  script:
    - pip install .[lint]
    - export LANG=en_US.UTF-8  # Otherwise, flake8 might fail with UnicodeDecodeError: 'ascii' codec can't decode byte
    - flake8

mypy:
  extends: .matrix_job
  stage: Code Quality
  script:
    - pip install -e .[lint]
    - mypy .

qsslint:
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Code Quality
  script:
    - run_headless $(find . -name "*.qss" | xargs qsslint)  # This assumes qsslint installed in the CI image

pre-commit:
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Code Quality
  script:
    - pip install -e .[lint]
   # Run pre-commit on the changes. If in MR form, we run for all commits in the MR,
   # otherwise just on the last commit.
    - pre-commit run --from-ref ${CI_MERGE_REQUEST_DIFF_BASE_SHA:-HEAD~1} --to-ref $CI_COMMIT_SHA

pytest:
  extends: .matrix_job
  stage: Unit Tests
  script:
    - |
      pip install .[test]
      extra_args=
      [[ "CURRENT_BASE_IMAGE" == "$ACCPY_IMAGE_CC7_2020_11" ]] && extra_args="--cov-report html:coverage --cov-report term-missing:skip-covered --cov=comrad --cov=_comrad --cov=_comrad_designer --cov=_comrad_examples"
      OMP_NUM_THREADS=1 run_headless python -m pytest \
        -p no:faulthandler \
        --random-order \
        --junitxml=report.xml \
        $extra_args \
        -x \
        --color=yes
  artifacts:
    name: coverage-report
    paths:
      - coverage
    when: on_success
    expire_in: 1 month
    reports:
      junit: report.xml

build wheel:
  extends: .acc_py_build_wheel
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Build Wheel

.sphinx_custom:
  stage: Documentation
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  before_script:
      - *init_sequence
      - yum install -y -q graphviz  # Required to generate inheritance diagrams
      - pip install .[doc]  # Need to install it here, as sphobjinv should be available
      - python -c "import sphobjinv as soi; [soi.fileops.writebytes(path=f'docs/{f}.inv', contents=soi.zlib.compress(soi.Inventory(plaintext=soi.fileops.readbytes(f'docs/{f}.txt')).data_file())) for f in ['qt', 'pydm', 'qsci', 'pyqt']]" # Prepare custom intersphinx inventory files

sphinx:
  extends:
    - .acc_py_build_docs
    - .sphinx_custom
  only:
    refs:
      - master
      - develop
      - /^feature\/.+$/

sphinx on tag:
  extends:
    - .acc_py_build_docs_on_tag
    - .sphinx_custom

release wheel on tag:
  extends: .acc_py_release_wheel
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Upload Release

release sdist on tag:
  extends: .acc_py_release_sdist_v2
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Upload Release

anybadge:
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Documentation
  script:
    - pip install anybadge
    - pip install .[lint,doc]
    - mkdir -p badges
    - BADGE_MYPY_VERSION="$(read -a mypy_output <<< "$(pip list | grep -E mypy[\t\ ])" && echo ${mypy_output[1]})"
    - BADGE_FLAKE8_VERSION="$(read -a flake8_output <<< "$(pip list | grep -E flake8[\t\ ])" && echo ${flake8_output[1]})"
    - BADGE_SPHINX_VERSION="$(read -a sphinx_output <<< "$(pip list | grep -E Sphinx[\t\ ])" && echo ${sphinx_output[1]})"
    - BADGE_COMRAD_VERSION="$(python -c 'import comrad; print(comrad.__version__)' | awk '{split($0,ver,"+");print ver[1]}')"
    - anybadge -l mypy -v "v${BADGE_MYPY_VERSION}" -f badges/mypy.svg -c olive -o
    - anybadge -l flake8 -v "v${BADGE_FLAKE8_VERSION}" -f badges/flake8.svg -c olive -o
    - anybadge -l acc-py-repo -v "comrad v${BADGE_COMRAD_VERSION}" -f badges/repo.svg -c purple -o
    - anybadge -l documentation -v "sphinx v${BADGE_SPHINX_VERSION}" -f badges/docs.svg -c teal -o
  artifacts:
    paths:
      - badges
    when: on_success
    expire_in: 1 day
  only:
    refs:
      - develop
